# -*- coding: utf-8 -*-
"""53f12b51-fbca-493f-820e-c3e5b55632de

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-02-0b35817aba3e/locations/us-east1/repositories/53f12b51-fbca-493f-820e-c3e5b55632de
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE SCHEMA IF NOT EXISTS fraud_data
# OPTIONS(
#  location="us",
#  default_table_expiration_days=14 );

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE EXTERNAL TABLE `qwiklabs-gcp-02-0b35817aba3e.fraud_data.fraud_data_table`
# OPTIONS (
#   format = 'CSV',
#   uris = ['gs://labs.roitraining.com/data-to-ai-workshop/fraud_data_raw.csv'],
#   skip_leading_rows = 1,
#   allow_jagged_rows = false,
#   allow_quoted_newlines = false,
#   field_delimiter = ',',
#   max_bad_records = 10
# );

# Commented out IPython magic to ensure Python compatibility.
# 
# %%bigquery
# CREATE OR REPLACE TABLE `qwiklabs-gcp-02-0b35817aba3e.fraud_data.fraud_training_data` AS (
#   SELECT
#     * EXCEPT (
#       Employment_Status, Device_Type, Age, Previous_Assistance_Received, Supporting_Doc_Verified
#     ),
#     CASE WHEN Employment_Status = 'Employed' THEN 1 ELSE 0 END AS emp_status_employed,
#     CASE WHEN Employment_Status = 'Unemployed' THEN 1 ELSE 0 END AS emp_status_unemployed,
#     CASE WHEN Employment_Status = 'Self-Employed' THEN 1 ELSE 0 END AS emp_status_self_employed,
#     CASE WHEN Device_Type = 'Mobile' THEN 1 ELSE 0 END AS device_type_mobile,
#     CASE WHEN Device_Type = 'Desktop' THEN 1 ELSE 0 END AS device_type_desktop,
#     CASE WHEN Device_Type = 'Tablet' THEN 1 ELSE 0 END AS device_type_tablet,
#     CASE
#       WHEN Age BETWEEN 18 AND 24 THEN '18-24'
#       WHEN Age BETWEEN 25 AND 34 THEN '25-34'
#       WHEN Age BETWEEN 35 AND 44 THEN '35-44'
#       WHEN Age BETWEEN 45 AND 54 THEN '45-54'
#       WHEN Age BETWEEN 55 AND 64 THEN '55-64'
#       ELSE '65+'
#     END AS age_bin,
#     SAFE_DIVIDE(Income, Amount_Requested) AS Income_to_Amount_Requested,
#     DATE_DIFF(CURRENT_DATE(), Previous_Assistance_Date, DAY) AS Time_Since_Previous_Assistance,
#     CAST(Previous_Assistance_Received AS INT64) AS Previous_Assistance_Received_int,
#     CAST(Supporting_Doc_Verified AS INT64) AS Supporting_Doc_Verified_int
#   FROM
#     `qwiklabs-gcp-02-0b35817aba3e.fraud_data.fraud_data_table`
# );