# -*- coding: utf-8 -*-
"""student-04-5859cc09764d (Aug 27, 2025, 3:48:22 PM)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-02-0b35817aba3e/locations/us-central1/repositories/8a6bd470-0767-4474-bfb0-688e1ca12f2d
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE SCHEMA IF NOT EXISTS weather_3_dataset
# OPTIONS(
# location="us",
# default_table_expiration_days=14 );

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
#  CREATE OR REPLACE EXTERNAL TABLE `qwiklabs-gcp-02-0b35817aba3e.weather_3_dataset.wx_data`
# OPTIONS (
# format = 'CSV',
# uris = ['gs://labs.roitraining.com/data-to-ai-workshop/weather_data.csv'],
# skip_leading_rows = 1,
# allow_jagged_rows = false,
# allow_quoted_newlines = false,
# field_delimiter = ',',
# max_bad_records = 10
# )
# ;

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE MODEL
# `qwiklabs-gcp-02-0b35817aba3e.weather_3_dataset.gemini_model` REMOTE
# WITH CONNECTION DEFAULT OPTIONS (ENDPOINT = 'gemini-2.0-flash');

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery forecast_output
# CREATE OR REPLACE TABLE
# `qwiklabs-gcp-02-0b35817aba3e.weather_3_dataset.forecast_output` AS (
# SELECT *
# FROM
# ML.GENERATE_TEXT(
# MODEL `weather_3_dataset.gemini_model`,
# (
# SELECT CONCAT(
# 'Provide a narrative weather forecast for the following data: ',
# date, city, state, temperature_f, wind_speed_mph, precipitation_in, barometric_pressure_inHg, humidity_percent, weather_condition) AS prompt
# FROM `qwiklabs-gcp-02-0b35817aba3e.weather_3_dataset.wx_data`
# ),
# STRUCT(
# 0.2 AS temperature, TRUE AS flatten_json_output, 1000 AS max_output_tokens)));